numbers = [2,1,2,4,5,2]
# print(numbers)
# numbers.append(9)
# print(numbers)
# numbers.extend([7,8,9])
# print(numbers)
# numbers.insert(0,99)
# print(numbers)
# numbers.insert(1,99)
# print(numbers)
# numbers.pop()
# print(numbers)
# numbers.sort()
# print(numbers)
# numbers.sort(reverse=True)
# print(numbers)
# numbers.reverse()
# print(numbers)
# numbers.clear()
# print(numbers)
print(numbers.count(2))

# print(sum(numbers))
# print(min(numbers))
# print(max(numbers))
# print(len(numbers))